config/routes.rb
Rails.application.routes.draw do
  root :to => 'books#index'
  resources :books, :except => [:new, :edit]

  resources :books
  resources :estados
  resources :prestamos
  resources :rols
  resources :tipo_identificacions
  resources :usuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    validates_presence_of :title, :author, :fecha_publicacion, :editorial
    has_many :prestamo
    belongs_to :estado
end

app/models/estado.rb
class Estado < ApplicationRecord
end

app/models/prestamo.rb
class Prestamo < ApplicationRecord
    belongs_to :estado
    belongs_to :usuario
    belongs_to :book
end

app/models/rol.rb
class Rol < ApplicationRecord
end

app/models/tipo_identificacion.rb
class TipoIdentificacion < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
    belongs_to :tipo_identificacion
    belongs_to :estado
    belongs_to :rol
    has_many :prestamo
    has_many :book throught :prestamo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
    render component: 'Books', props: {books: @books}
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    respond_to do |format|
      format.json do
        if @book.save
          render :json => @book
        else
          render :json => { :errors => @book.errors.messages}, :status => 422
        end
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    @book = Book.find(params[:id])
    respond_to do |format|
      format.json do
        if @book.update(book_params)
          render :json =>@book
        else
          render :json => { :errors => @book.errors.messages }, :status => 422          
        end
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :fecha_publicacion, :editorial)
    end
end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController
 before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /estados
  # GET /estados.json
  def index
    @estados = Estado.all
    render component:'Estados', props: {estados:@estados}
  end

  # GET /estados/1
  # GET /estados/1.json
  def show
  end

  # GET /estados/new
  def new
    @estado = Estado.new
  end

  # GET /estados/1/edit
  def edit
  end

  # POST /estados
  # POST /estados.json
  def create
    @estado = Estado.new(estado_params)
    respond_to do |format|
      if @estado.save
        format.html { redirect_to @estado, notice: 'Estado was successfully created.' }
        format.json { render :show, status: :created, location: @estado }
      else
        format.html { render :new }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estados/1
  # PATCH/PUT /estados/1.json
  def update
    respond_to do |format|
      if @estado.update(estado_params)
        format.html { redirect_to @estado, notice: 'Estado was successfully updated.' }
        format.json { render :show, status: :ok, location: @estado }
      else
        format.html { render :edit }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estados/1
  # DELETE /estados/1.json
  def destroy
    @estado.destroy
    respond_to do |format|
      format.html { redirect_to estados_url, notice: 'Estado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estado
      @estado = Estado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estado_params
      params.require(:estado).permit(:abreviatura, :descripcion)
    end
end

app/controllers/prestamos_controller.rb
class PrestamosController < ApplicationController
end

app/controllers/rols_controller.rb
class RolsController < ApplicationController
end

app/controllers/tipo_identificacions_controller.rb
class TipoIdentificacionsController < ApplicationController
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/prestamos_helper.rb
module PrestamosHelper
end

app/helpers/rols_helper.rb
module RolsHelper
end

app/helpers/tipo_identificacions_helper.rb
module TipoIdentificacionsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :book_title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author, id: :book_author %>
  </div>

  <div class="field">
    <%= form.label :fecha_publicacion %>
    <%= form.date_select :fecha_publicacion, id: :book_fecha_publicacion %>
  </div>

  <div class="field">
    <%= form.label :editorial %>
    <%= form.text_field :editorial, id: :book_editorial %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Fecha publicacion</th>
      <th>Editorial</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.fecha_publicacion %></td>
        <td><%= book.editorial %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Fecha publicacion:</strong>
  <%= @book.fecha_publicacion %>
</p>

<p>
  <strong>Editorial:</strong>
  <%= @book.editorial %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/estados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Estados</h1>

<table>
  <thead>
    <tr>
      <th>Abreviatura</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estados.each do |estado| %>
      <tr>
        <td><%= estado.abreviatura %></td>
        <td><%= estado.descripcion %></td>
        <td><%= link_to 'Show', estado %></td>
        <td><%= link_to 'Edit', edit_estado_path(estado) %></td>
        <td><%= link_to 'Destroy', estado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estado', new_estado_path %>

app/views/estados/new.html.erb
<h1>New Estado</h1>

<%= render 'form', estado: @estado %>

<%= link_to 'Back', estados_path %>